### ISSUE TITLE
QR code is not working ok

### ISSUE THREAD

**Issue by dmborque314** [geordanr/xwing#146]
Hi: I've found that QR ganerated is not valid sometimes. For example, with this squad 

{"version":"0.1.1","faction":"rebels","pilots":[{"name":"bluesquadronpilot","ship":"bwing","upgrades":{"system":["firecontrolsystem"]}},{"name":"bluesquadronpilot","ship":"bwing","upgrades":{"system":["firecontrolsystem"]}},{"name":"roarkgarnet","ship":"hwk290","upgrades":{"turret":["blasterturret"],"crew":["chewbacca"],"title":["moldycrow"]}},{"name":"airencracken","ship":"z95headhunter","upgrades":{"ept":["swarmtactics"]}}]}

the QR generated is not valid (I'm using this web decoder: http://zxing.org/w/decode.jspx).

But if I remove Airen from the squad, then the QR generated is valid.

**Comment by geordanr** [comment]
The new minimal QR that I'm generating seems to work now; I tried uploading the resulting QR code to that site and it was able to parse it.

Google Goggles is able to scan and parse the code.

I tried scanning it into your builder and the scanner does find the QR code, but the squad doesn't load; not sure why.  I was able to scan and load other squad QRs into your builder though, so something's definitely working.

Closing this since it scans in multiple readers; reopen if you're still having issues.

**Comment by dmborque314** [comment]
Thanks! The XWS I sent now works.
Other XWS might not work, perhaps a bad implementation of the xws spec on
my side. Do you remember which squad didn't load on my app?
Greetings!
David

2015-01-14 20:15 GMT+01:00 Geordan Rosario <notifications@github.com>:

**Comment by geordanr** [comment]
This squad: https://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v3!s!44:36,-1,-1,-1:-1:-1:;44:36,-1,-1,-1:-1:-1:;46:37,33:3:-1:;67:9,-1:-1:-1:

**Comment by dmborque314** [comment]
It works for me. I scan it into my app and it loads ok.


2015-01-15 0:36 GMT+01:00 Geordan Rosario <notifications@github.com>:

**Comment by geordanr** [comment]
Okay.  Maybe it was just a transient problem.

**Comment by dmborque314** [comment]
Great! Thanks!

2015-01-15 0:39 GMT+01:00 Geordan Rosario <notifications@github.com>:
