### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by ibrahimerol** [geordanr/xwing#295]
Hello;
I'm İbrahim from Turkey. I'm a FoW player and new to X-Wing Miniatures. While searching for Squad Builders I found your site, and I think that its most user friendly one. I'm not perfect in English but I can translate to Turkish as good as I can. I'm an Electrical Engineer and I commonly translate documents or reports to Turkish. If you need Turkish site, I can do it for enjoy. Besides I'll learn while I translate. Not too much web design experience, but I can translate texts easily. If you interested my mail is ibrahimerol1981@gmail.com
Thanks

**Comment by geordanr** [comment]
That would be great!

Translations are stored in translation files in the `coffeescripts/` directory.  They are named `cards-XX.coffee` where `XX` is the two letter ISO-639-1 abbreviation for the language (for Turkish, it's `tr`, so the new file would be `cards-tr.coffee`).  You can look at existing translations at https://github.com/geordanr/xwing/tree/master/coffeescripts (for example: [Spanish](https://github.com/geordanr/xwing/blob/master/coffeescripts/cards-es.coffee), [Russian](https://github.com/geordanr/xwing/blob/master/coffeescripts/cards-ru.coffee)).

If you're comfortable with using git and GitHub, the easiest way to contribute would be to [make a fork](https://help.github.com/articles/fork-a-repo/) of this repository, create a new translation file, and submit it as part of a [pull request](https://help.github.com/articles/using-pull-requests/).

Otherwise, you can send me the translation file, stored somewhere handy like [Gist](https://gist.github.com/), and put the link here as a reply to this issue thread.

Let me know if you have any questions!

**Comment by ibrahimerol** [comment]
Ok, thanks for datailed instructions. My office computer not allowed to download GitHub Desktop (server firewall), but I'll try at home. If I have a problem I'll ask you.

**Comment by ibrahimerol** [comment]
Hi again. I still have problems with GitHub. Is it okay if get copy of a translation file and edit it wih a source code editor (Notepad++ or Ultraedit), and save as a .txt file? Now I'm trying with Notepad++ and it is easier than I thought, Ctrl+H is doing most of job well :)

**Comment by ibrahimerol** [comment]
https://gist.github.com/ibrahimerol/1bb307d4e306bff35e5b
Here is the menus and basic ui translation. Can you upload this file to see is it ok? Next step: "Cards"

**Comment by geordanr** [comment]
I've tested the file locally and it looks good so far.  The only issue is on line 101 in the translation for `.bbcode-list` -- there is an extra quote `'` between "BBCode" and "u kopyalayın ve...".  Once I removed that quote everything worked.

**Comment by ibrahimerol** [comment]
Hello. I have complated whole translation finally. It takes longer than I expected, happly i finished it (i hope that). If every thing is Ok I'll be glad to see it online. I'll ask for feedbacks from more experienced players in Turkey.

**Comment by geordanr** [comment]
Thanks!  I'll get this online.
