### ISSUE TITLE
Non-FAQ'd cards

### ISSUE THREAD

**Issue by tomekk666** [geordanr/xwing#514]
Hello there!

First off, let me say thanks for the excellent web app you've provided, its pretty much always open whenever we are playing X-Wing. :D However, as our local group only just acquired a Jumpmaster, would it be possible to have an option to show non-FAQ'd versions of cards/upgrades? We do not play competitively so the option would be much appreciated.

**Comment by geordanr** [comment]
Unfortunately having multiple versions of the same card is not supported in the builder.  My intent is for the builder to provide only competition-legal builds, so that someone isn't able to show up to a tournament with an illegal list built with my builder.

(Also, even though you do not play competitively, I recommend using the FAQ'd version of the JumpMasters.  They are much less awful -- and thus more fun -- to play against.)
